# Generated by Django 3.2.4 on 2021-06-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='imagealbum',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
