# Generated by Django 3.2.4 on 2021-06-09 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.imagealbum'),
        ),
    ]
